@baseUrl = http://localhost:3333

### Health check
GET {{baseUrl}}/health

### Get rooms
GET {{baseUrl}}/rooms

### Create room
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "sala de teste",
  "description": "Essa é uma sala de teste"
}

### Get room questions
GET {{baseUrl}}/rooms/637fe503-b247-4b4b-bf87-e14f2b8f873a/questions